### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by ghost** [PocketMine/RubberBand#6]
Hey man, why don't you just make a proxy like BungeeCord, it connects to servers by sending join requests and emulate the first part of the login.

**Comment by ghost** [comment]
yea!

**Comment by iksaku** [comment]
@kvwang98 I think that it will be the same thing... but with more functions, knowing @shoghicp I believe that this will be awesome for you and other plugin makers :D

**Comment by shoghicp** [comment]
@kvwang98 well, it is going to do that, but needs a single TCP connection to pass UDP messages

**Comment by ghost** [comment]
@shoghicp I mean just like a normal client send normal requests then start redirecting packets. 
And it doesn't require client install the plugin and I don't think we need a TCP connection. xD

**Comment by shoghicp** [comment]
Remember that this is UDP, not different state in the same socket is saved. A socket would have to be created per client. This works right for 50 clients. Get more and everything will lag. Having a single TCP connection reduces the amount of sockets needed to one per server.

MCPE is completly different than MCPC, and we have to bypass the auth part (start sending chunks directly, pass the UDP packet stream counts to maintain the same connection, and refill recovery buffers. In MCPC that is not needed since all the counts and such are handled by TCP itself. Remember, we handle more low-level things than MCPC

**Comment by ghost** [comment]
@shoghicp So the MCPE protocol is bad. #BlameMojang
